name: snap
on:
  push:
    branches:
      - foxy
  pull_request:
    branches:
      - foxy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      snap: ${{ steps.build-snap.outputs.snap }}
    strategy:
      matrix:
        architecture:
        - linux/amd64
        - linux/arm64
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: build-snap
      with:
        snapcraft-args: '--enable-experimental-extensions'

    # Make sure the snap is installable
    - run: |
        sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}

    # @todo Do some testing with the snap
    - run: |
        micro-ros-agent udp4

  publish:
    if: github.ref == 'refs/heads/foxy'
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        architecture:
        - linux/amd64
        - linux/arm64
    steps:
    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ needs.build.outputs.snap }}
        release: edge

